env:
  browser: true
  jquery: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'

parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    jsx: true

plugins:
  - react

rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
      FunctionExpression:
        parameters: first
      CallExpression:
        arguments: first
      ArrayExpression: first
      ObjectExpression: first
      ImportDeclaration: first
      ignoredNodes:
        - JSXAttribute
        - JSXSpreadAttribute

  linebreak-style:
    - error
    - unix
  quotes:
    - off
  semi:
    - error
    - always
  max-len:
    - warn
    - code: 120
  one-var:
    - warn
    - initialized: never
      uninitialized: always
  eqeqeq:
    - error
    - smart
  dot-location:
    - error
    - property
  wrap-iife:
    - error
    - inside
  block-spacing:
    - error
    - always
  camelcase:
    - error
    - properties: never
  func-style:
    - warn
    - declaration
    - allowArrowFunctions: true
  padded-blocks:
    - error
    - never
  quote-props:
    - warn
    - consistent-as-needed
  space-before-function-paren:
    - warn
    - anonymous: never
      named: never
      asyncArrow: always
  brace-style:
    - error
    - 1tbs
  array-bracket-spacing: error
  array-callback-return: error
  arrow-spacing: error
  comma-dangle:
    - error
    - only-multiline  # or always-multiline? (== require dangling commas)
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  constructor-super: error
  curly: error
  eol-last: error
  func-call-spacing: error
  func-name-matching: error
  generator-star-spacing: error
  implicit-arrow-linebreak: error
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  lines-between-class-members: error
  max-statements-per-line: error
  new-cap: error
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  object-shorthand: warn
  operator-assignment: error
  operator-linebreak:
    - error
    - after
    - overrides:
        ?: before
        :: before
  prefer-arrow-callback: warn
  prefer-const: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: warn
  radix: error
  require-yield: error
  rest-spread-spacing: error
  semi-spacing: error
  space-in-parens: error
  space-infix-ops: error
  space-before-blocks: warn
  space-unary-ops: error
  spaced-comment: error
  strict: error
  switch-colon-spacing: error
  symbol-description: error
  template-curly-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  yield-star-spacing: error
  yoda: error
  no-unmodified-loop-condition: error
  no-unsafe-negation: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: warn
  no-class-assign: error
  no-confusing-arrow: error
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-eval: error
  no-implied-eval: error
  no-floating-decimal: warn
  no-global-assign: error
  no-implicit-globals: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-mixed-operators: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxBOF: 0
      maxEOF: 0
  no-new-func: error
  no-new-object: error
  no-new-symbol: error
  no-return-assign: error
  no-octal-escape: warn
  no-new-wrappers: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-tabs: error
  no-this-before-super: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  no-void: error
  no-whitespace-before-property: error
  no-with: error
  no-shadow:
    - warn
    - allow: [data]
  no-use-before-define:
    - error
    - functions: false
      classes: false
  nonblock-statement-body-position: error
  # rules from eslint-plugin-react
  react/button-has-type: warn
  react/default-props-match-prop-types: error
  react/destructuring-assignment: warn
  react/display-name: error
  react/forbid-component-props: error
  react/no-access-state-in-setstate: warn
  react/no-array-index-key: warn
  react/jsx-boolean-value: error
  react/jsx-closing-bracket-location:
    - error
    - after-props
  react/jsx-closing-tag-location: error
  react/jsx-curly-brace-presence: error
  react/jsx-curly-spacing: error
  react/jsx-equals-spacing: error
  react/jsx-first-prop-new-line:
    - error
    - never
  react/jsx-filename-extension: error
  react/jsx-indent: error
  # XXX: our style is not supported yet, so nothing to enforce (see yannickcr/eslint-plugin-react#398)
  react/jsx-indent-props: off
  react/jsx-key: error
  react/jsx-no-comment-textnodes: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-target-blank: error
  react/jsx-no-undef: error
  react/jsx-pascal-case: error
  react/jsx-tag-spacing:
    - error
    - closingSlash: never
      beforeSelfClosing: always
      afterOpening: never
      beforeClosing: never
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-wrap-multilines: error
  react/no-children-prop: error
  react/no-danger-with-children: error
  react/no-deprecated: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: error
  react/no-is-mounted: error
  react/no-multi-comp:
    - warn
    - ignoreStateless: true
  react/no-redundant-should-component-update: error
  react/no-render-return-value: error
  react/no-string-refs: error
  react/no-this-in-sfc: error
  react/no-typos: error
  react/no-unescaped-entities:
    - error
    - forbid: ['>', '}']
  react/no-unknown-property: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/no-will-update-set-state: error
  react/prefer-es6-class: error
  react/prop-types: error
  react/react-in-jsx-scope: error
  react/require-default-props: warn
  react/require-render-return: error
  react/self-closing-comp: error
  react/sort-comp: warn
  react/void-dom-elements-no-children: error

globals:
  _: false
  $T: false
  K: false
  moment: false
  Indico: false
  IndicoUI: false
  build_url: false
  alertPopup: false
  confirmPrompt: false
  handleFlashes: false
  handleAjaxError: false
  ajaxDialog: false
  cornerMessage: false
  enableIfChecked: false
  global: false
  require: false
